# Generated by Django 4.1.3 on 2022-12-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAnimales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='animales',
            new_name='animal',
        ),
    ]
